MengTo/Spring

README.md, Spring.podspec
We should update the tag after merge
=> Add CocoaPods support

README.md, Spring/Spring.swift, Spring/SpringButton.swift, Spring/SpringImageView.swift, Spring/SpringLabel.swift, Spring/SpringTextField.swift, Spring/SpringTextView.swift, Spring/SpringView.swift
=> Added repeatCount as an editable property

Spring/Spring.swift
based on what I said here:
https://github.com/MengTo/Spring/issues/16
The views were retaining the Spring, and the Spring was also retaining the view.
=> prevents retain cycle

Spring/AsyncButton.swift, Spring/AsyncImageView.swift, SpringApp.xcodeproj/project.pbxproj
For loading images asynchronously
=> Added AsyncImageView and AsyncButton

Spring/Spring.swift, SpringApp/SpringViewController.swift
I want to try other easing functions because Spring has only five easing functions, "spring", "linear", "easeIn", "easeOut", "easeInOut".
I added easing functions.
Here are easing functions I added.
http://easings.net/
=> Add easing functions

Spring/DesignableTabBarController.swift, Spring/LoadingView.swift, Spring/Misc.swift, Spring/Spring.swift, SpringApp/OptionsViewController.swift, SpringApp/SpringViewController.swift
Support swift 1.2. Test in Xcode 6.3 beta 4
=> Support swift 1.2

README.md
@MengTo: To allow installs via Cocoapods for version 1.0.2, you need to make an updated tag of the repository that includes the latest changes.
=> README Pod update and whitespace

Spring/AutoTextView.swift
Now it can be used by importing Spring (with CocoaPods).
=> Make AutoTextView class public

Spring/BlurView.swift
Practical use:
`insertBlurView(view, style: .Dark).addGestureRecognizer(gestureRecognizer)`
=> BlurView returns the view

README.md, Spring.podspec, Spring/BlurView.swift, Spring/DesignableLabel.swift, Spring/DesignableTabBarController.swift, Spring/DesignableTextField.swift, Spring/DesignableTextView.swift, Spring/ImageLoader.swift, Spring/Info.plist, Spring/KeyboardLayoutConstraint.swift, Spring/LoadingView.swift, Spring/Misc.swift, Spring/SoundPlayer.swift, Spring/SpringAnimation.swift, Spring/TransitionManager.swift, Spring/TransitionZoom.swift, SpringApp.xcodeproj/project.pbxproj, SpringApp.xcodeproj/xcshareddata/xcschemes/Spring.xcscheme, SpringApp.xcodeproj/xcshareddata/xcschemes/SpringApp.xcscheme, SpringApp/Info.plist, SpringApp/SpringViewController.swift, SpringAppTests/Info.plist, SpringTests/Info.plist
This should be merged when Xcode 7 and Swift 2 are ready for production. This also closes #71.
=> [WIP] Swift 2

README.md
=> Remove the redudant word in readme.md

README.md, Spring/AutoTextView.swift, Spring/BlurView.swift, Spring/DesignableButton.swift, Spring/DesignableImageView.swift, Spring/DesignableTabBarController.swift, Spring/DesignableTextField.swift, Spring/DesignableTextView.swift, Spring/DesignableView.swift, Spring/ImageLoader.swift, Spring/KeyboardLayoutConstraint.swift, Spring/LoadingView.swift, Spring/Misc.swift, Spring/SoundPlayer.swift, Spring/Spring.swift, Spring/TransitionManager.swift, Spring/TransitionZoom.swift, SpringApp/Base.lproj/LaunchScreen.xib, SpringApp/CodeViewController.swift, SpringApp/OptionsViewController.swift, SpringApp/SpringViewController.swift
=> Updated to Xcode 8 beta 4

Spring/ImageLoader.swift, Spring/Misc.swift, Spring/SoundPlayer.swift, Spring/Spring.swift, Spring/SpringAnimation.swift, Spring/SpringButton.swift, Spring/SpringImageView.swift, Spring/SpringLabel.swift, Spring/SpringTextField.swift, Spring/SpringTextView.swift, Spring/SpringView.swift, Spring/TransitionManager.swift, Spring/TransitionZoom.swift, SpringApp/AppDelegate.swift, SpringApp/SpringViewController.swift
=> Updated for Xcode 8 beta 6

Spring/SpringButton.swift, Spring/SpringImageView.swift, Spring/SpringLabel.swift, Spring/SpringTextField.swift, Spring/SpringTextView.swift, Spring/SpringView.swift
My attempt at updated based of the issue I created [#197](https://github.com/MengTo/Spring/issues/197)
=> Updated Access Control to 'open' for SpringView derivatives

Spring/ImageLoader.swift
Issue https://github.com/MengTo/Spring/issues/209 Swift 3
=> Fix asynchronous image cache

Spring/ImageLoader.swift
I met an issue when the image download failed because of timeout, data set to nil. Check must added before adding to cache.
=> Add check against nil before adding to cache

Spring/DesignableLabel.swift, Spring/DesignableTextField.swift, Spring/DesignableTextView.swift
issue #267 fix for the swift4 version.
=> Quick fix to placeHolder crash, removal of bang operator.

Spring/Misc.swift, Spring/Spring.swift
=> Replace deprecated type

Spring/DesignableTabBarController.swift, Spring/LoadingView.swift, Spring/TransitionManager.swift, Spring/TransitionZoom.swift
support for Xcode 8.2.1 and Swift 2.3
=> support for Xcode 8.2.1 and Swift 2.3

Spring/Misc.swift
=> Substring deprecated fix

Spring/Spring.swift
Implemented change suggested in #131.
=> Fix repeat count in the swing animation

Spring/Spring.swift
ref: #232 
Implemented change suggested in #137.
=> Fix repeat count in the flip animation

Spring.podspec, Spring/KeyboardLayoutConstraint.swift, Spring/LoadingView.swift
Updated podspec file for tvOS. Eliminated class KeyboardLayoutConstraint on tvOS. Eliminated class LoadingView on tvOS.
=> Added support for tvOS.

Spring/DesignableTabBarController.swift, Spring/Misc.swift, SpringApp.xcodeproj/project.pbxproj
Dear @MengTo , please review it.
=> Upgrade  code to support swift 5
